package objects


class SYError {
    var errorDesc = ""
    var error: Int? = 0

    enum class Error {
        OK,
        USER_NULL,
        NICKNAME_EXISTS,
        INVALID_INFO,
        USER_EXISTS,
        USER_EXISTS_OR_WRONG,
        GENERIC_ERROR,

        WRONG_PASSWORD,
        NOT_ENOUGH_BALANCE,
        NO_STAFF_AVAILABLE,

        USER_NOT_AUTHENTICATED,
        ACCOUNT_NOT_VALIDATED,

        ACTION_NO,
        BAD_INFO_SENT,
        TEAM_EXISTS,
        TEAM_DOESNT_EXISTS,
        TEAM_INVITE_DOESNT_EXISTS,
        TEAM_CANNOT_DELETE_OWNER,
        TEAM_ALREADY_IN_TOURNAMENT,

        MEMBER_NOT_FOUND,
        MEMBER_WRONG_CREDENTIALS,
        MEMBER_NAUGHTY,
        MEMBER_VAL_TOS,
        BAD_USERNAME,
        BAD_TAG,
        BAD_PASSWORD,
        PLAYER_NOT_ENOUGH_PERMISSIONS,
        PLAYER_DOESNT_BELONG_TO_TEAM,
        PLAYER_ALREADY_IN_TOURNAMENT,
        PLAYER_NOT_ENOUGH_BALANCE,
        PLAYER_CANNOT_BE_PAID,

        EMPTY_GAME_ID,
        TOURNAMENT_CANT_QUIT,
        TOURNAMENT_TEAM_COUNT_INVALID,
        TOURNAMENT_CANT_REPORT,
        TOURNAMENT_CANT_VERIFY,
        TOURNAMENT_CANT_COLLECT,
        TOURNAMENT_NOT_FOUND,
        TOURNAMENT_CANNOT_BE_EDITED,
        TOURNAMENT_CANCELED,
        TOURNAMENT_DISABLED,
        TOURNAMENT_CANT_KICKSTART,
        TOURNAMENT_INVALID_INFO,
        TOURNAMENT_ERROR,
        TOURNAMENT_CANT_JOIN_ROSTER,
        TOURNAMENT_CANT_LEAVE,
        TOURNAMENT_CANT_BE_PAID,
        TOURNAMENT_THIRD_MATCH_NOT_YET_REPORTED,
        TOURNAMENT_RESULT_MATCH_ALREADY_HAS_WINNER,
        TOURNAMENT_USER_IS_PART_OF_NEXT_MATCH,
        TOURNAMENT_FIFTH_MATCH_NOT_YET_REPORTED,
        TOURNAMENT_CANT_JOIN,
        TOURNAMENT_MATCH_NOT_FOUND,

        MONEY_EARNED_EXISTS,
        MONEY_WAS_SPENT,
        CURRENCY_NOT_SUPPORTED,

        DB_ERROR,
        SERVER_COMMUNICATION_ERROR,
        FILE_UPLOAD_ERROR,
        WRONG_FREQUENCY,
        BAD_CAPTCHA,

        // stream_all_users
        STREAM_NO_MORE_RECORDS_FOUND
    }
}
